spring:
  config:
    import: aws-secretsmanager:devops-secretmanager

  datasource:
    url: jdbc:postgresql://appdb-instance.ck1qmoy0wjp6.us-east-1.rds.amazonaws.com:5432/appdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      instance-profile: true
management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    io.awspring.cloud.secretsmanager: DEBUG   # 👈 enables debug logs so you can confirm secrets are loaded
    org.springframework: INFO
    com.devops: DEBUG